### ISSUE TITLE
[UI] Show a Snackbar on task creation or failure

### ISSUE THREAD

**Issue by ritiksaxena124** [ritiksaxena124/trello-app-clone#3]
#### Current Behavior
There is no _snackbar_  is shown after a task gets created or fails to be created.

#### Desired Behavior
Show _snackbar_ after the task gets created or if there is any error.

**Comment by abhishekpaturkar** [comment]
Can I use toast for this issue

**Comment by ritiksaxena124** [comment]
Yup @abhishekpaturkar , you can use the [react-hot-toast](https://www.npmjs.com/package/react-hot-toast) library.
